import React from "react";

const Title = "Ripplemail";
export default {
    Title,
    title_home: "Home",
    title_dashboard: "Dashboard",
    title_notifications: "Notifications",
    city_prompt: "Choose a city",
    company_prompt: "Choose a company",
    cafeteria_prompt: "Choose a cafeteria",
    login_text: "SignIn",
    login_text2: " enter email & password to continue",
    forgot_text1: "Reset Your Password",
    forgot_text2: "you need One Time Password to reset password",
    signup_text: "SignUp",
    signup_text2: "Let's get started",
    mobileHint: "Enter Mobile Number",
    passwordHint: "Enter Password",
    confPasswordHint: "Enter Confirm Password",
    nameHint: "Enter Name",
    emailHint: "Enter Email",
    phoneHint: "Enter Phone",
    numberHint: "0123-456-789",
    signup: "SIGNUP",
    signin: "SIGNIN",
    sendOTP: "SEND OTP",
    resetpassword: "Reset Password",
    forgetPassword: "Forgot Password ?",
    otpText: "OTP Verification",
    otpSendText: "We will send you One Time Password on this mobile number",
    otpSendMobile: `Enter OTP send to mobile`,
    enterMobile: "Enter Mobile Number",
    generateOTP: "Generate OTP",
    notReceiveOTP: "don't receive the OTP",
    resendOTP: "Resend OTP",
    id: 0,
    lang: "English",
    langCode: "en",
    signinTitle: "Signin to Get Started!",
    email: "Email",
    name: "Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    createAcc: "Create Account",
    forgot: "Forgot Password",

    reset: "Reset",
    logout: "Logout",

    home: "Home",
    categories: "Categories",
    settings: "Settings",

    // App intro sliders
    slide1Title: "SAMPLE TITLE 1",
    slide1Text: "This is sample description 1",
    slide2Title: "SAMPLE TITLE 2",
    slide2Text: "This is sample description 2",
    slide3Title: "SAMPLE TITLE 3",
    slide3Text: "This is sample description 3",

    //Validation messages
    required: "is required",
    notValid: "is not valid",
    tooShort: "Minimum {count, number} chars required",
    doesntMatch: "doesn't match",

    nameErrorMessage: "Please Enter Correct Name",
    phoneErrorMessage: "Please Enter Correct Mobile Number",
    emailErrorMessage: " Please Enter Correct Email",
    passwordErrorMessage: "Password must be atleast 8 characters",
    confirmPasswordErrorMessage: "Password and confirm password doesnot match",
    emptynameErrorMessage: "Please Enter your Name",
    emptyphoneErrorMessage: " Please Enter Mobile Number",
    emptyemailErrorMessage: " Please Enter  Email",
    emptyotpErrorMessage: " Please Enter OTP",
    otpErrorMessage: " Please Enter Correct OTP",
    emptypasswordErrorMessage: "Please Enter password",
    emptyconfirmPasswordErrorMessage: "Please Enter confirm  password",
    successfullVerify: "Successfully verified your Mobile Number",
    enterValidOTP: "Please enter valid OTP send to your Mobile Number",
    passwordResetSuccess: "Password successfully reset",
    searchHint: "Search here...",
    addressHint: "Enter Address",
    cityHint: "Enter City",
    stateHint: "Enter State",
    save: "Save",
    login_emailinput_hint: "Enter Email/Mobile",
    register: "Register",
    login: "Log In",
    restepwd: "Reset Password",
    verify: "Verify",
    otpHint: "Enter correct OTP",
    ChangeNumber: "Change Number",
    ForgotPassword: "Forgot Password ?",
    OtpNotReceived: "OTP Not Received ?",
    ResendOtp: " Resend OTP",
    RequestOTP: "Request OTP",
    serverErrorMessage: "Please try after sometime!",
    VerifyPhone: "Verify Phone",
    Change: "Change?",
    OTPsentto : "OTP sent to ",
    full_name:"Full Name",
    first_name:"First Name",
    last_name:"Last Name",
    name_hint:"Enter Full Name",
    first_name_hint:"Enter First Name",
    last_name_hint:"Enter Last Name",
    mobile:"Mobile Number",
    gender_text:"Your Gender",
    locality_text:"Locality",
    locality_hint:"Your Locality",
    pincode_text:"Pincode",
    pincode_hint:"Your 6 digit PinCode",
    city_text:"City/District/Town",
    city_hint:"City/District/Town",
    state_text:"State",
    state_hint:"State",
    address_text:"Address",
    address_hint:"Your Address",
    landmark_text:"LandMark",
    landmark_hint:"Your LandMark",
    address_type:"Address Type",
    country_text:"Country"

};
